//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIPM_ECommerce_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTable
    {
        public int TId { get; set; }
        public Nullable<decimal> TAmount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TURL { get; set; }
    }
}
